### PR TITLE
Fix this.config undefined for model limit

### PR DESCRIPTION
**Pull request by catrielmuller**
This.config is undefined using this packs

``` json
{
name: "core",
version: "1.0.1"
},
{
name: "repl",
version: "1.0.8"
},
{
name: "router",
version: "1.0.8"
},
{
name: "express",
version: "1.0.14"
},
{
name: "waterline",
version: "1.0.0-beta-1"
},
{
name: "footprints",
version: "1.0.1"
}
```

### CODE REVIEW

**Comment by catrielmuller** [comment]
Fix find when you try to limit the query by limit argument like:

```
/api/model?limit=x
```

Fixed the problem with the defaultlimit in the update ( https://github.com/trailsjs/trailpack-waterline/issues/13 )
I dont know if some need one limit when try to update a lots of objects but i replace the default limit per one param for do this explicitly

**Comment by jaumard** [comment]
Is this ready to merge @catrielmuller ?

**Comment by catrielmuller** [comment]
Sure, why not?

**Comment by jaumard** [comment]
Just to be sure :) this a good for me, merging...

**Pull request merged**
